### ISSUE TITLE
Fails to bootstrap with VPN mode enabled (oreo?)

### ISSUE THREAD

**Issue by sarevok-anchev** [guardianproject/orbot#151]
Recently installed android 8(.1) on a device.

Orbot works fine, until VPN mode is enabled - then, it never bootstraps at all.
Disabling VPN mode makes bootstraping work again, and connectivity is there.

Got Orbot running on a few Nougat devices, same Orbot version, no problems.

Can anyone reproduce this?

Installed from f-droid by the way - latest version.

**Comment by n8fr8** [comment]
There is a new beta release build to try:
https://github.com/n8fr8/orbot/releases/tag/16.0.2-BETA-3

the "armeabi-v7a" APK should work for most people, or just get the "universal" one if you aren't sure.

**Comment by sarevok-anchev** [comment]
Same issue. Goes up to "Bootstrapped 85%: Finishing handshake with first hop", and I suspect it only gets that far because something was already cached.

Do you have any devices running oreo with which you can try to reproduce this? I have one more, but it's the exact same ROM and exact same model, so..

**Comment by n8fr8** [comment]
Have you tried this with the RC-1 release?

i developed on Oreo and can't reproduce it.

**Comment by sarevok-anchev** [comment]
Same issue, unfortunately.

Is your Oreo device also running LineageOS ?

**Comment by sarevok-anchev** [comment]
Forgot to mention, also tried on the second device with a brand new install of LOS 15.1.

Installed orbot from f-droid - everything else is pristine -and it doesn't go beyond "Starting polipo process".

And then, a few minutes later, "Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up (waiting for circuit) repeated a few times.

Ports 443, 9001, 9011.

**Comment by pgerber** [comment]
I've observed this behavior too. I always assumed it was a Lineage issue, 14.1 in my case, and thus decided to ignore it.

I created two debug logs, one where I started Orbot with VPN enabled and one where I started Orbot with VPN disabled and then enabled it:

[log_start_then_enable_vpn.txt](https://github.com/n8fr8/orbot/files/2018818/log_start_then_enable_vpn.txt)
[log_start_with_vpn_enabled.txt](https://github.com/n8fr8/orbot/files/2018819/log_start_with_vpn_enabled.txt)

Either way, I can no longer connect to the internet after enabling VPN.

**Comment by derengland** [comment]
The same Problem here with LineageOS 15.1 20180716 for the S5 G900F (klte). The Orbot-Version is 16.0.2-RC-1
Has anyone a solution found yet?

**Comment by kykeon** [comment]
I am running into the same issue with LineageOS 15.1, latest build. Toggling VPN mode makes orbot not able to bootstrap. Toggling it again, and restarting Tor connectivity by pressing the main round button results in a successful bootstrap, but no VPN mode, which is needed as many apps don't support Orbot directly..

@n8fr8 any idea what might be causing this? LOS or orbot?

**Comment by kykeon** [comment]
@xYuusha @pgerber: Did either of you ever find a solution?

@n8fr8: Is this the best place to report Orbot bugs, for future reference? Tor trac seems pretty idle..

**Comment by n8fr8** [comment]
Yes, I'm not a big fan of trac, and Orbot is more a guardianproject/n8fr8 project than torproject managed one anyhow

**Comment by kykeon** [comment]
@n8fr8 sent you an email some days ago, was it received?

To sum it up, it seems according to the comments here that this is a LOS 15.1 (and derivates) issue, but I am not yet fully sure.

You mentioned developing on Oreo and not encountering the issue. Was it LOS?

Are you in a position to test with LOS and confirm that it is broken?

Personally I have tested with 3 different models and LOS 15.1, they all show this issue.

**Comment by kykeon** [comment]
FWIW I suspect this to be an actual Orbot bug, as other VPN apps work just fine with LOS 15.1.

**Comment by amostyaev** [comment]
I have the same issue on Resurrection Remix (Oreo 8.1). Bootstrapping stucks on 10%.

**Comment by kykeon** [comment]
Some other people have the same problem..

https://www.reddit.com/r/LineageOS/comments/9ck0ko/any_luck_with_los_151_and_orbot_tor/
https://www.reddit.com/r/TOR/comments/7oax84/vpn_feature_in_orbot_dont_working_anymore_in/ (no, granting storage permission doesn't fix it)

**Comment by gggomg** [comment]
> I have the same issue on Resurrection Remix (Oreo 8.1). Bootstrapping stucks on 10%.

Same, latest Ressurection Remix 6.2.0 (Oreo 8.1).

**Comment by sfpauly** [comment]
I have this same issue, as soon as I turn on VPN, connectivity ends. I'm running LineageOS 15.1 (Android 8.1) on a Samsung Galaxy Tab S2 (SM-T713). I didn't have this issue on Nougat with same device. This appears unique to Oreo.

**Comment by ddxor** [comment]
I'm also affected as described by @sarevok-anchev. Mostly stuck at Bootstrapping 85%.

LineageOS 15.1-20181106-NIGHTLY. Android 8.1.0.

**Comment by xYuusha** [comment]
For anyone who might be interested, looks like this was fixed on 9.0. Sadly, I think that upgrading is the only real fix.

**Comment by xYuusha** [comment]
James Anslow <notifications@github.com> wrote:
> Do you mean Android 9? I.e. Pie? If so, is this the Lineage Pie build? What are you testing that on?

Sorry, I forgot to clarify.
I did meant android Pie. I'm using lineage 16 and orbot installed from fdroid without any kind of problem.
It looks like either the problem was only oreo related or I'm quite lucky.

**Comment by sarevok-anchev** [comment]
@xYuusha You are quite lucky. I have installed an unofficial LOS 16 and suffer from a similar but not exactly equal problem.

This time, Tor (orbot) bootstraps just fine with VPN mode enabled, but the apps chosen for VPN mode simply do not work.

I don't know exactly what the problem is, but OpenVPN for Android suffers from a similar problem.
I have found in my research that there are two modes to set-up OpenVPN for android: all apps go through VPN except selected, or only selected apps go through VPN.

In OpenVPN for Android, and I have confirmed that the same problem happens with LOS 15.1, selecting apps to go through VPN is completely broken - they just bypass the VPN.

However, all apps except selected is also broken (but at least it works - somewhat): no matter which apps are selected, **all** of them go through the VPN ..


I wonder if something has changed in VPN handling since Oreo that is causing these issues. Perhaps apps that make use of VPN mode must be updated to reflect these changes.

@n8fr8 may have something to say about the matter..

Until then I encourage everyone affected by this bug to attempt to duplicate my findings.
It seems, based on previous comments, that this is not LOS-specific.

**Comment by sarevok-anchev** [comment]
https://www.reddit.com/r/LineageOS/comments/9zcpaz/lineageos_vpn_bug/

**Comment by sarevok-anchev** [comment]
https://jira.lineageos.org/browse/BUGBASH-2567

If anybody else could make some noise ..

By the way, still not sure whether this is really a LOS bug or not. There seems to be some evidence pointing that way, see [here](https://github.com/schwabe/ics-openvpn/issues/972) (and if you can reproduce, please share).

**Comment by sarevok-anchev** [comment]
Neither @n8fr8 nor the LineageOS developers appear to be very interested in sorting this out unfortunately.

To this day I don't know where the problem actually is - orbot, lineageos, something else.

All I know is that in Nougat Orbot VPN mode worked fine, and with Oreo and Pie (LineageOS) it doesn't. To make matters worse, not every LineageOS user seems to be affected.

**Comment by zndrsblurry** [comment]
I encountered this problem when I flashed unofficial lineage OS 16 android pie on my samsung galaxy s5, orbot fails to bootstrap. Before I flashed android pie, everything is working fine with orbot. It seems that orbot has really a bug rather than the OS because when I installed orxy with the add on orxify, everything worked great.

**Comment by sarevok-anchev** [comment]
Just tried with the latest Orbot available on f-droid, with Oreo (LineageOS), and VPN mode still fails to bootstrap, FWIW.

**Comment by derengland** [comment]
That is true for me, I also couldn't get orbot running in vpn-mode with LOS 16. My solution: i downloaded LOS 14 for my S5 and with this orbot runs. 
PS: LOS 14 for S5 is available per https://archive.org/index.php

**Comment by lunar-debian** [comment]
Dumping my thought on this issue after fighting for a couple of hours:

As far as I understood My take is that there's an incompatibility between the kernel used by LineageOS on older device and how are implemented routing aspects of the [VPN API](https://developer.android.com/guide/topics/connectivity/vpn) that probably have changed since 15.1. 

This would explain why users of LineageOS 15.1+ on more recent devices do not experience the issue, and why it works on older devices with LineageOS 14.1.

On LineageOS 14.1, I can do (where 10052 is the uid of a selected app in Orbot):
```
# su 4242
$ ip route get 192.0.2.1                                                
192.0.2.1 via 192.168.1.254 dev if23  src 192.168.1.106  uid 4242 
    cache
$ cat /sys/class/net/wlan0/ifindex
23
# su 10052
$ ip route get 192.0.2.1                                                                         
192.0.2.1 dev if25  src 192.168.200.1  uid 10052 
    cache
$ cat /sys/class/net/tun0/ifindex
25
```

We see the correct output interface has been selected by the kernel. When under LineageOS 16.0, I believe it always showed the interface index corresponding to `wlan0`, but I sadly lost command history. Would anyone experiencing the issue care to try and see what result they get? Would anyone *not* experiencing the issue under LineageOS 15.1+ try as well?

Thanks. :)

**Comment by alexdevos** [comment]
Hello !
I have a similar problem : two phones almost the same (but different : Samsung Galaxy S5 LTE & Samsung Galaxy S5+) with LineageOS 16, Orbot works with one phone but not the other ! 

Orbot version used : orbotMAX-16.1.3-BETA-2-tor-0.4.1.6-rc-fullperm-armeabi-v7a-release.apk

### Primary phone : doesn't work !

Model : SM-G901 klte (Samsung Galaxy S5 LTE)
OS : LineageOS 16 (Android 9) (https://download.lineageos.org/klte) (rom file : lineage-16.0-20200116-nightly-klte-signed.zip)
Kernel : 3.4.113-lineageos-g9fc6b38
Bootloader : G900FXXS1CQD1

RPV mode with default LineageOS browser with URL https://check.torproject.org : "_Sorry. You are not using Tor._"

Log in Orbot :
```
checking binary version: null
upgrading binaries to latest version: 0.4.1.6-openssl1.0.2p
Waiting for control port...
checking binary version: 0.4.1.6-openssl1.0.2p
mise à jour des paramètres dans le service Tor
updating torrc custom configuration...
success.
Orbot démarre...
Tor configuration VERIFIED.
Waiting for control port...
Connecting to control port: 34637
SUCCESS connected to Tor control port.
SUCCESS - authenticated to control port.
Démarrage du client Tor... terminé.
adding control port event handler
SUCCESS added control port event handler
Tor started; process id=3942
NOTICE: Bootstrapped 5% (conn): Connecting to a relay 
NOTICE: Bootstrapped 10% (conn_done): Connected to a relay 
Using control port to shutdown Tor
sending HALT signal to Tor process
checking binary version: 0.4.1.6-openssl1.0.2p
mise à jour des paramètres dans le service Tor
updating torrc custom configuration...
success.
Orbot démarre...
Tor configuration VERIFIED.
Waiting for control port...
Connecting to control port: 38334
SUCCESS connected to Tor control port.
SUCCESS - authenticated to control port.
Démarrage du client Tor... terminé.
adding control port event handler
NOTICE: Bootstrapped 5% (conn): Connecting to a relay 
SUCCESS added control port event handler
Tor started; process id=3994
NOTICE: Bootstrapped 10% (conn_done): Connected to a relay 
NOTICE: Bootstrapped 14% (handshake): Handshaking with a relay 
NOTICE: Bootstrapped 15% (handshake_done): Handshake with a relay done 
NOTICE: Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection 
NOTICE: Bootstrapped 25% (requesting_status): Asking for networkstatus consensus 
NOTICE: Bootstrapped 30% (loading_status): Loading networkstatus consensus 
NOTICE: I learned some more directory information, but not enough to build a circuit: We have no usable consensus. 
NOTICE: Bootstrapped 40% (loading_keys): Loading authority key certs 
NOTICE: The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services. 
NOTICE: Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors 
NOTICE: I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6271, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.) 
NOTICE: Bootstrapped 50% (loading_descriptors): Loading relay descriptors 
NOTICE: The current consensus contains exit nodes. Tor can build exit and internal paths. 
NOTICE: I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 997/6271, and can only build 0% of likely paths. (We have 16% of guards bw, 15% of midpoint bw, and 17% of exit bw = 0% of path bw.) 
NOTICE: Bootstrapped 56% (loading_descriptors): Loading relay descriptors 
NOTICE: Bootstrapped 62% (loading_descriptors): Loading relay descriptors 
NOTICE: Bootstrapped 67% (loading_descriptors): Loading relay descriptors 
NOTICE: Bootstrapped 72% (loading_descriptors): Loading relay descriptors 
NOTICE: Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits 
NOTICE: Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits 
NOTICE: Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits 
NOTICE: Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits 
NOTICE: Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits 
NOTICE: Bootstrapped 95% (circuit_create): Establishing a Tor circuit 
NOTICE: Bootstrapped 100% (done): Done 
```


### Backup phone : works !

Model : SM-G901F kccat6 (Samsung Galaxy S5+)
OS : LineageOS 16 (Android 9) (https://download.lineageos.org/kccat6) (rom file : lineage-16.0-20200117-nightly-kccat6-signed.zip)
Kernel : 3.10.108-g6d89fa5
Bootloader : G901FXXU1CRH4

RPV mode with default LineageOS browser with URL https://check.torproject.org/ : "_Congratulations. This browser is configured to use Tor._"

Log in Orbot :
```
checking binary version: null
upgrading binaries to latest version: 0.4.1.6-openssl1.0.2p
Waiting for control port...
checking binary version: 0.4.1.6-openssl1.0.2p
mise à jour des paramètres dans le service Tor
updating torrc custom configuration...
success.
Orbot démarre...
Tor configuration VERIFIED.
Waiting for control port...
Connecting to control port: 41786
SUCCESS connected to Tor control port.
SUCCESS - authenticated to control port.
Démarrage du client Tor... terminé.
Using control port to shutdown Tor
sending HALT signal to Tor process
checking binary version: 0.4.1.6-openssl1.0.2p
mise à jour des paramètres dans le service Tor
updating torrc custom configuration...
success.
Orbot démarre...
Tor configuration VERIFIED.
Waiting for control port...
Connecting to control port: 42357
SUCCESS connected to Tor control port.
SUCCESS - authenticated to control port.
Démarrage du client Tor... terminé.
adding control port event handler
SUCCESS added control port event handler
Tor started; process id=2707
NOTICE: Bootstrapped 5% (conn): Connecting to a relay 
NOTICE: Bootstrapped 10% (conn_done): Connected to a relay 
NOTICE: Bootstrapped 14% (handshake): Handshaking with a relay 
NOTICE: Bootstrapped 15% (handshake_done): Handshake with a relay done 
NOTICE: Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection 
NOTICE: Bootstrapped 25% (requesting_status): Asking for networkstatus consensus 
NOTICE: Bootstrapped 30% (loading_status): Loading networkstatus consensus 
NOTICE: I learned some more directory information, but not enough to build a circuit: We have no usable consensus. 
NOTICE: Bootstrapped 40% (loading_keys): Loading authority key certs 
NOTICE: The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services. 
NOTICE: Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors 
NOTICE: I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6239, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.) 
NOTICE: Bootstrapped 50% (loading_descriptors): Loading relay descriptors 
NOTICE: The current consensus contains exit nodes. Tor can build exit and internal paths. 
NOTICE: I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 498/6239, and can only build 0% of likely paths. (We have 6% of guards bw, 6% of midpoint bw, and 7% of exit bw = 0% of path bw.) 
NOTICE: Bootstrapped 57% (loading_descriptors): Loading relay descriptors 
NOTICE: Bootstrapped 64% (loading_descriptors): Loading relay descriptors 
NOTICE: Bootstrapped 69% (loading_descriptors): Loading relay descriptors 
NOTICE: Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits 
NOTICE: Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits 
NOTICE: Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits 
NOTICE: Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits 
NOTICE: Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits 
NOTICE: Bootstrapped 95% (circuit_create): Establishing a Tor circuit 
NOTICE: Bootstrapped 100% (done): Done 
```


Maybe I should do a clean reinstallation of LineageOS on my primary phone but I have so many apps to reinstall and parameters to set... 
If it helps, don't hesitate to ask me for more details/logs.

**Comment by Kreyren** [comment]
Same issue here using oneplus2 on LOS16

**Comment by TheDuchy** [comment]
+1 with klte LOS16

**Comment by Kreyren** [comment]
FWIW Tor Browser is working fine on my end

**Comment by n8fr8** [comment]
> FWIW Tor Browser is working fine on my end

Tor Browser doesn't have VPN mode or start on boot, but thanks for the input!

**Comment by Kreyren** [comment]
@n8fr8 Any idea on what is causing this issue?

or any ETA on the fix?

(i would be interested in trying to fix this)

**Comment by TheDuchy** [comment]
@n8fr8 Tor browser works just fine, but not Orbots VPN

**Comment by h0ek** [comment]
On my Sony Xperia Z3 Compact with LineageOS 16.0.20200421-NIGHTLY-z3c
VPN Mode doesn't work. It urns ON, allow to select apps in Tor-Enabled Apps menu but application traffic is not passed through Tor :(

**Comment by Kreyren** [comment]
FWIW same issue on OnePlus2 using AOSP Extended (Android 10)

**Comment by h0ek** [comment]
I didn't test it yet but I found info that Orbot 16.0.5-RC-2 works fine https://guardianproject.info/releases/ I will check it later and let you know

**Comment by Kreyren** [comment]
I have the issue on version `16.1.4-RC-1-tor-0.4.2.5-rc`  with `0.4.2.5-openssl1.0.2p`

**Comment by bluetrees2** [comment]
I believe I identified the broken part.

In short. Policy based routing with `uidrange` is broken.

## Longer Explanation

### 1. Introducing the relationship of Android's VPN service to linux policy based routing

The bug is related to the way the "VpnService" works. Android create a routing table for every network interface for example `wlan0` and `rmnet0`, and for VPN it typically names it `tun0` or `tun1` these tables can be seen with `ip route show table [table name]` for example:
```shell
$ ip route show table tun0

default dev tun0 proto static scope link 
1.1.1.1 dev tun0 proto static scope link 
192.168.200.1 dev tun0 proto static scope link 
```

When VPN is turned on android redirects network traffic to the VPN interface "tun0" using policy based routing which can be seen with `ip rule show`. The output looks like:
```diff
 0:      from all lookup local 
 10000:  from all fwmark 0xc0000/0xd0000 lookup legacy_system 
 10500:  from all iif lo oif dummy0 uidrange 0-0 lookup dummy0 
 10500:  from all iif lo oif wlan0 uidrange 0-0 lookup wlan0 
+11000:  from all iif tun0 lookup local_network 
+12000:  from all fwmark 0x0/0x20000 iif lo uidrange 0-10185 lookup tun0 
+12000:  from all fwmark 0x0/0x20000 iif lo uidrange 10187-99999 lookup tun0 
+12000:  from all fwmark 0xc0069/0xcffff lookup tun0 
 13000:  from all fwmark 0x10063/0x1ffff iif lo lookup local_network 
 13000:  from all fwmark 0x10064/0x1ffff iif lo lookup wlan0 
+13000:  from all fwmark 0x10069/0x1ffff iif lo uidrange 0-10185 lookup tun0 
+13000:  from all fwmark 0x10069/0x1ffff iif lo uidrange 10187-99999 lookup tun0 
+13000:  from all fwmark 0x10069/0x1ffff iif lo uidrange 0-0 lookup tun0 
 14000:  from all iif lo oif dummy0 lookup dummy0 
 14000:  from all iif lo oif wlan0 lookup wlan0 
 14000:  from all iif lo oif tun0 uidrange 0-10185 lookup tun0 
 14000:  from all iif lo oif tun0 uidrange 10187-99999 lookup tun0 
 15000:  from all fwmark 0x0/0x10000 lookup legacy_system 
 16000:  from all fwmark 0x0/0x10000 lookup legacy_network 
 17000:  from all fwmark 0x0/0x10000 lookup local_network 
 19000:  from all fwmark 0x64/0x1ffff iif lo lookup wlan0 
 21000:  from all fwmark 0x69/0xffff lookup wlan0 
 22000:  from all fwmark 0x0/0xffff iif lo lookup wlan0 
 23000:  from all fwmark 0x0/0xffff uidrange 0-0 lookup main 
 32000:  from all unreachable
```
The rules highlighted in green are the ones that android added specifically for orbot's VPN mode on my device. The one relevant to this issue is `from all fwmark 0x0/0x20000 iif lo uidrange NNNNN-NNNNN lookup tun0` the break it down of it means route through `tun0` all network traffic from apps in the uid range `0-10185` and `10187-99999` skipping uid `10186` which on my phone belongs to Orbot. The packet mark part `fwmark 0x0/0x20000` is for allowing traffic with the `0x20000` bit AKA the `protectFromVpn` bit which is set on a socket basis using the api function [`VpnService.protect(socket)`](https://developer.android.com/reference/android/net/VpnService#protect(java.net.Socket)) to allow a socket connection to escape the VPN. Typically It is used to make sure the VPN can escape itself otherwise it won't connect to the internet.

### 2. The bug

Now getting to the bug itself. All of the rules shown above are correct and in a normal Android ROM everything should be fine but on buggy ROMs the clauses `uidrange 0-10185` and `10187-99999` don't have the intended effect. More specifically, at the time when there rules are interpreted by the kernel all network traffic for some reason has uid `0` irrespectably of which application it originated from. If uid `0` is not included in the `uidrange`; all traffic will escape the VPN, and if uid `0` is included in the `uidrange`; then no traffic will escape the VPN interface including Orbot and tor themselves which is why tor fails to bootstrap.

To demonstrate. (Need root access and a shell)
```shell
# This should teel it to make uid 0 escape the VPN but instead all apps will escape
ip rule del from all fwmark 0x0/0x20000 iif lo uidrange 0-10185 lookup tun0 priority 12000
ip rule add from all fwmark 0x0/0x20000 iif lo uidrange 1-10185 lookup tun0 priority 12000
```

### 3. Conclusion

Someone who is more familiar with how `ip rule` is implemented internally should debug why it thinks that all traffic belongs to uid `0`.

**Comment by bluetrees2** [comment]
If you have root access you can use `iptables` for a workaround meanwhile the kernel patches are backported for the affected devices (see [lineageos#2193](https://gitlab.com/LineageOS/issues/android/-/issues/2193))

For an example of the `iptables` workaround. In a root shell run the following commands:
```shell
orbotuid=`dumpsys package org.torproject.android | grep userId | cut -d= -f2 - | cut -d' ' -f1 -`
iptables -t mangle -A OUTPUT -m owner --uid-owner $orbotuid -j MARK --set-mark 0x20000/0x20000
ip6tables -t mangle -A OUTPUT -m owner --uid-owner $orbotuid -j MARK --set-mark 0x20000/0x20000
iptables -t nat -A POSTROUTING -m mark --mark 0x20000/0x20000 -j MASQUERADE
ip6tables -t nat -A POSTROUTING -m mark --mark 0x20000/0x20000 -j MASQUERADE
```
This should fix Orbot.

For convenience I made a root app that uses this approach which allows to fix Orbot and additionally make a VPN whitelist in just a few clicks. Find the app along with the source code in my repo [bluetrees2/novpn/releases](https://github.com/bluetrees2/novpn/releases).

**Comment by blurbitt** [comment]
> If you have root access you can use `iptables` for a workaround meanwhile the kernel patches are backported for the affected devices (see [lineageos#2193](https://gitlab.com/LineageOS/issues/android/-/issues/2193))
> 
> For an example of the `iptables` workaround. In a root shell run the following commands:
> 
> ```shell
> orbotuid=`dumpsys package org.torproject.android | grep userId | cut -d= -f2 - | cut -d' ' -f1 -`
> iptables -t mangle -A OUTPUT -m owner --uid-owner $orbotuid -j MARK --set-mark 0x20000/0x20000
> ip6tables -t mangle -A OUTPUT -m owner --uid-owner $orbotuid -j MARK --set-mark 0x20000/0x20000
> iptables -t nat -A POSTROUTING -m mark --mark 0x20000/0x20000 -j MASQUERADE
> ip6tables -t nat -A POSTROUTING -m mark --mark 0x20000/0x20000 -j MASQUERADE
> ```
> 
> This should fix Orbot.
> 
> For convenience I made a root app that uses this approach which allows to fix Orbot and additionally make a VPN whitelist in just a few clicks. Find the app along with the source code in my repo [bluetrees2/novpn/releases](https://github.com/bluetrees2/novpn/releases).

It works on Lineage OS 17.1, Thank you.

**Comment by n8fr8** [comment]
Thanks for all the input, debugging and quick fix apps. Maybe we can consider adding some "root" code back into Orbot to deal with these kind of cases.
